# backend/monitoring/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          service: 'node'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          service: 'cadvisor'

  - job_name: 'django'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:8000']
        labels:
          service: 'django'
          environment: 'production'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
        labels:
          service: 'postgres'

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']
        labels:
          service: 'rabbitmq'
          
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
        labels:
          service: 'postgres_exporter'
  - job_name: 'rabbitmq_exporter'
    static_configs:
      - targets: ['rabbitmq_exporter:9419']
        labels:
          service: 'rabbitmq_exporter'