scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # CORRECTION : Scraper l'exporter PostgreSQL, pas Postgres directement
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
        labels:
          service: 'postgres'

  # CORRECTION : Scraper l'exporter RabbitMQ, pas RabbitMQ directement
  - job_name: 'rabbitmq_exporter'
    static_configs:
      - targets: ['rabbitmq_exporter:9419']
        labels:
          service: 'rabbitmq'

  # Configuration Django
  - job_name: 'django'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:8000']
        labels:
          service: 'django'